

version: "3.1"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - node1
      - node2
      - node3
    restart: always
    ports:
      - '8080:8080'
    networks:
      - boardme

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    networks:
      - boardme

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    networks:
      - boardme

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    networks:
      - boardme


  mongo:
    image: mongo
    expose:
      - "27017"
    networks:
      - boardme


networks:
  boardme: